### ISSUE TITLE
`JSON.STRAPPEND` isn't implemented.

### ISSUE THREAD

**Issue by tombatron** [tombatron/NReJSON#1]
I tried a few different things, but I'm just not sure how this command works so I wasn't able to add support for it.

**Comment by samgithub** [comment]
It works like this.  If I have a JSON record like:

address: "{\"street\":\"678 Winona\",\"city\":\"New Medford\",\"state\":\"New York\",\"zip\":\"12345\"}"

then

json.strappend key .address.street '" Boulevard"'

results in .address.street --- > 678 Winona Boulevard

It is "similar" to the INCR command.  -- but just for string Type.  It gives strange results if used for a numeric field (like zip )
