### ISSUE TITLE
JsonGetAsync not working

### ISSUE THREAD

**Issue by samgithub** [tombatron/NReJSON#10]
I just installed v3 of Nrejson

The following code retuns:
**{"type":4,"isNull":false}**

 RedisResult result = await dbLocal.JsonGetAsync("mykey");
            return result;
*** *** *** *** 
**The v2 code** 
var result = await dbLocal.JsonGetAsync("mykey");
            return result;

worked
*** *** *** *** 
redis-cli returns the correct json

json.get mykey   -- > Works

**Comment by tombatron** [comment]
So the version 3 code doesn't work at all?

I'm not sure I'm tracking what you're telling me.

Could you provide me a more complete example?

**Comment by samgithub** [comment]
OK  -- I'll recreate a simple example/solution based on sample data from your integration tests and get it back to you with my results.  -- Should have it ready later today.

Thanks for your quick response.

**Comment by samgithub** [comment]
Turns out I wasn't properly Stringify-ing the data on SAVE  the response.  Please CLOSE this issue.
