### ISSUE TITLE
Support Full Framework net461 and net472

### ISSUE THREAD

**Issue by benguenter** [tombatron/NReJSON#11]
Stackexchange Redis does build binaries for the full frameworks net461 and net472.
Is there a reason why NReJSON doesn't build for the same?

As far as I can tell, the only thing that would need to change is some default keywords being changed over to null. (language features)
Do you mind if I submit a PR for that change?
My scenario requires net461 to be used rather than .netstandard 2.0.

**Comment by tombatron** [comment]
I targeted .NET Standard 2.0 in order to support .NET Framework and .NET
Core consumers.

That said, are you sure that my usage of the ‘default’ keyword is the
blocker here?

**Comment by benguenter** [comment]
Ah, you are right, I was targeting an older MSBuild version when I built `NReJSON` so it complained about the newer language features.
The only thing required to target net461 and net472 is adding the `TargetFrameworks` tag in the `csproj`.

Referencing a NetStandard package from a full framework solution causes a bunch of side effects.
For example, when building, msbuild loads some DLLs from the netstandard library that have different versions than are found in the netframework library and can cause significant headaches when trying to find the right version to reference.

There are far fewer issues with using NetStandard from net472 than with 461 but at this time we cannot upgrade to net472.
It's for these reasons that `Stackexchange.Redis` already publishes a build specifically for these framework versions also.

**Comment by tombatron** [comment]
Fair enough. 

I'll see what I can do about targeting net461 and net472 directly.

**Comment by tombatron** [comment]
@benguenter I just published version 3.1 of the package to Nuget. It should be available soon, it's multi-targeted to 461, 472, and NET Standard 2.0. 

Let me know if that works for you!

**Comment by benguenter** [comment]
This is awesome! Thanks a bunch, @tombatron!

**Comment by tombatron** [comment]
No problem!
