### ISSUE TITLE
Support json.toggle and json.clear commands

### ISSUE THREAD

**Issue by oshadmi** [tombatron/NReJSON#13]
Add support for the following commands:
`json.toggle`
`json.clear`

**Comment by tombatron** [comment]
So I've tried the commands `JSON.TOGGLE` and `JSON.CLEAR` and I know they exist but I can't find any documentation on them. Can you help me out?

**Comment by oshadmi** [comment]
Documentation is not yet available (@emmanuelkeller please correct me if I'm wrong)

Basically,
`json.toggle` is toggling bool values (from false to true, from true to false) returning the new value (ignoring non-boolean paths)

`json.clear` is clearing/emptying arrays and objects (to have zero slots/keys without deleting the array/object) returning the count of cleared paths (ignoring non-array and non-objects paths)

You can also review tests ([toggle](https://github.com/RedisJSON/RedisJSON/blob/c636d8fdb74eba01362bc104b204ec1d38bec04b/tests/pytest/test.py#L333), [clear](https://github.com/RedisJSON/RedisJSON/blob/c636d8fdb74eba01362bc104b204ec1d38bec04b/tests/pytest/test.py#L446))

**Comment by tombatron** [comment]
Alrighty, all set. 

I just published NReJSON 3.3.
