### ISSUE TITLE
Add support for RedisJSON 2.0 full JSONPath syntax

### ISSUE THREAD

**Issue by gkorland** [tombatron/NReJSON#18]
Please notice all the commands can now get full jsonpath, i.e. dynamic paths that start with a $ sign.
As a result all the commands can now return multi parts of the JSON.
see: https://oss.redis.com/redisjson/commands/

**Comment by tombatron** [comment]
@gkorland I've got a branch (https://github.com/tombatron/NReJSON/tree/redisjson-2-cleanup) going to address the support for  dynamic paths and multiple results.

However, the commands with JSONPath only seem to work if I'm using the "preview" version of the `redislabs\rejson` docker container. 

Any idea with RedisJson 2.0 is coming out of preview?

**Comment by tombatron** [comment]
Verified that the last version of NReJSON supports paths (hopefully) correctly. ;)
