### ISSUE TITLE
Need to update StackExchange.Redis nuget pack version to lates

### ISSUE THREAD

**Issue by dariusdev** [tombatron/NReJSON#23]
<PackageReference Include="StackExchange.Redis" Version="2.5.61" /

**Comment by tombatron** [comment]
So the way I have "StackExchange.Redis" reference, the package manager should be fine with  you installing whatever version of the library you want, as long as it's a 2.x version. 

`<PackageReference Include="StackExchange.Redis" Version="2.*" />`

**Comment by dariusdev** [comment]
ok thnx :) my bad
