### ISSUE TITLE
redisjson indexing

### ISSUE THREAD

**Issue by jphaugla** [tombatron/NReJSON#7]
Add redisjson indexing to NReJSON.    From https://github.com/RedisJSON/RedisJSON, support:

json.set user2 $ '{"last":"Joan", "first":"Mc"}' INDEX person"
json.index add person last $.last
JSON.QGET person Jo*

**Comment by tombatron** [comment]
Hey Jason!

Thanks for the heads up on this. 

Any idea when these commands will be available in the "latest" docker image? Or should I be using some kind of nightly or something?

**Comment by gkorland** [comment]
You can use the `edge` tag

**Comment by tombatron** [comment]
So I added support for those new commands. 

I noticed when doing the integration tests that the indexing seems to only work on values stored in db 0.

Is that because Redis is moving away from the concept of "databases"?

Also, any feedback on my PR would be super if you have time.
